### ISSUE TITLE
How many rules?

### ISSUE THREAD

**Issue by Zyles** [DeltaSystems/aws-fail2ban#1]
How many rules does this script create? AWS WAF charges $1 per rule.

Will each fail2ban record be one rule?

Looking for some information at what type of cost this will end up at.

Thanks.

**Comment by bdelamatre** [comment]
This script interacts with an IPSet, which I don't believe has a cost. You can then use the IPSet for a block action on a single rule on a WAF. The same WAF/Rule can service multiple resources. Overall, this has been very cost effective for us.

**Comment by Zyles** [comment]
Ok thanks I looked more into it and saw there were ip lists within the rules.

Will try it out.
